artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/essharmavi/coccidiosis_chicken_disease_classifier/blob/main/Chicken-fecal-images.zip
  local_data_file: artifacts/data_ingestion/chicken_fecal_images.zip
  unzipped_data_dir: artifacts/data_ingestion

